### ISSUE TITLE
Adding support of emoji feature in susi server

### ISSUE THREAD

**Issue by saketkumar95** [fossasia/susi_server#72] opened 2017-01-27 19:30 UTC
Currently susi server doesn't have the support to emoji characters. We can add feature as most of the have this feature.

**Comment by jig08** [comment] 2017-01-27 22:36
Closing this, duplicate of Issue https://github.com/fossasia/susi_server/issues/3

**Closed by jig08** 2017-01-27 22:36 UTC

**Comment by saketkumar95** [comment] 2017-01-27 22:42
@jig08 i was asked [here](https://github.com/fossasia/susi_android/issues/462) to open this issue. :)

**Comment by jig08** [comment] 2017-01-27 22:43
Pls follow up on the previous one then :)
