### ISSUE TITLE
SUSI isn't replying to queries correctly

### ISSUE THREAD

**Issue by DNS-404** [fossasia/susi_server#739] opened 2018-05-22 17:28 UTC
**Actual Behaviour**

SUSI isn't replying to queries correctly as per skills.

**Expected Behaviour**

It should reply as per the skills. Example- For the query "pictures of cat", it should give an image of cat.

**Screenshots of the issue**

<img width="500" alt="screen shot 2018-05-22 at 10 54 55 pm" src="https://user-images.githubusercontent.com/31174685/40379381-89b665cc-5e13-11e8-9ccc-bd3c4aea239b.png">

**Would you like to work on the issue?**

Yes, I'm trying to figure out the problem.

**Comment by Orbiter** [comment] 2018-05-22 18:38
I admit that I was the one who merged https://github.com/fossasia/chat.susi.ai/commit/f13827c7467eefe55962435aac3975e2641924f3 
from the pull request https://github.com/fossasia/chat.susi.ai/pull/1024
which is the cause for the problem. Please open an issue in chat.susi.ai.

Please do not do such kind of "let the client answer questions" hacks. It will fail for so many reasons (i.e. wrong language). I should have rejected the pull request.

Here: not a bug!

**Comment by Orbiter** [comment] 2018-05-22 19:21
fixed with https://github.com/fossasia/susi_server/commit/556910575dbeff005257f11054dd017815683ab4

**Closed by Orbiter** 2018-05-22 19:21 UTC
