### ISSUE TITLE
Delete Chat Message API for chat.susi.ai

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi_server#846] opened 2018-06-17 21:24 UTC
**Actual Behaviour**

Not present

**Expected Behaviour**

A user should be able to delete messages

**Steps to reproduce it**

Required by: https://github.com/fossasia/chat.susi.ai/issues/1325

**Would you like to work on the issue?**

No

**Comment by akshatnitd** [comment] 2018-06-19 10:29
Closing since, this is a duplicate of #631

**Closed by akshatnitd** 2018-06-19 10:29 UTC
