### ISSUE TITLE
Set up automatic deployment to Google Cloud

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#85] opened 2017-02-12 14:59 UTC
There should be two automatic deployments to Google cloud
a) from the development branch and
b) from the master branch.

We can do in-depth testing this way. As the projects advances further, it is also possible to add a staging branch.

**Comment by Abhi2424shek** [comment] 2017-02-13 00:37
Duplicate of #65 close anyone of them pls. Thank you.

**Closed** 2017-04-05 12:13 UTC
Labels: enhancement
